### ISSUE TITLE
English documentation and comments

### ISSUE THREAD

**Issue by lululombard** [CamiAlfa/M365-BLE-PROTOCOL#4]
Hi !
I'm really sorry... but I don't understand a word of spanish.
Could someone translate at least the documentation ?
Thank you.

**Comment by net-monitor** [comment]
I send the message in English.. answered me or I talk with ebay support

בתאריך יום ה׳, 26 ביולי 2018, 01:41, מאת lululombard ‏<
notifications@github.com>:

**Comment by lululombard** [comment]
Hmmm. You realize that this is a GitHub issue right ?

**Comment by net-monitor** [comment]
Sory :)

בתאריך 26 ביולי 2018 11:02,‏ "lululombard" <notifications@github.com> כתב:

Hmmm. You realize that this is a GitHub issue right ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/CamiAlfa/M365-BLE-PROTOCOL/issues/4#issuecomment-408012213>,
or mute the thread
